(defun color-theme-dust ()
  (interactive)
  (color-theme-install
   '(color-theme-dust
     ((background-color . "#1c1c1c")
      (background-mode . light)
      (border-color . "#171717")
      (cursor-color . "#f5f4f4")
      (foreground-color . "gray")
      (mouse-color . "black"))
     (fringe ((t (:background "#171717"))))
     (mode-line ((t (:foreground "#000000" :background "#404936"))))
     (region ((t (:background "#2f03a5"))))
     (font-lock-builtin-face ((t (:foreground "#31d3c4"))))
     (font-lock-comment-face ((t (:foreground "#e81122"))))
     (font-lock-function-name-face ((t (:foreground "#ed8a0c"))))
     (font-lock-keyword-face ((t (:foreground "#cf4a44"))))
     (font-lock-string-face ((t (:foreground "#25ef29"))))
     (font-lock-type-face ((t (:foreground"#ca34e2"))))
     (font-lock-constant-face ((t (:foreground "gray"))))
     (font-lock-variable-name-face ((t (:foreground "#fefc58"))))
     (minibuffer-prompt ((t (:foreground "#b3d0ef" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'color-theme-dust)

